apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-mongo
  name: ashu-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashu-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-mongo
    spec:
      volumes: # creating volumes  
      - name: ashu-db-vol 
        persistentVolumeClaim: # calling pvc
          claimName: ashu-pvc # name of pvc 
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts: # to mount the volume 
        - name: ashu-db-vol # using above created volume
          mountPath: /data/db/ # mounting in default mongo location
        envFrom: # calling secret directry 
        - secretRef:
            name: db-cred 
status: {}
