apiVersion: v1
kind: PersistentVolume
metadata:
  name: ashu-pv # name of pv 
spec:
  capacity:
    storage: 2Gi # required space 
  accessModes:
    - ReadWriteOnce # RWO , RWM , ROM 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # my storage class
  hostPath: 
    path: /exto/ashu-space  
    type: DirectoryOrCreate # ifnot present then create above location
